CREATE TABLE IF NOT EXISTS AUTHORS
(
	AUTHORID INT NOT NULL AUTO_INCREMENT,
    FIRSTNAME VARCHAR(20) NOT NULL,
    LASTNAME VARCHAR(30)NOT NULL,
    PRIMARY KEY (AUTHORID)
);
CREATE TABLE IF NOT EXISTS TITLES
(
	ISBN VARCHAR(20) NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    EDITIONNUMBER INT NOT NULL,
    COPPYRIGHT VARCHAR(4) NOT NULL,
    PRIMARY KEY (ISBN)
);

CREATE TABLE IF NOT EXISTS AUTHORISBN
(
	AUTHORID INT NOT NULL,
    ISBN VARCHAR(20) NOT NULL,
    FOREIGN KEY (AUTHORID) REFERENCES AUTHORS(AUTHORID),
    FOREIGN KEY (ISBN) REFERENCES TITLES(ISBN)
)